// Structured extraction from Bright-Data-fetched BattleBots wiki pages.
//
// The fan wiki renders a "portable infobox" with machine-readable fields
// (data-source="team" | "weapons" | "weight" | "power" | "drive"). Those pages are
// 403-blocked to a plain scraper, so this parser only has anything to read *because*
// the HTML was fetched through Bright Data's Web Unlocker.
//
// Used by scrape.mjs. Also runnable on its own against already-saved evidence
// (no API calls, no credits spent):
//
//   node scraper/parse-specs.mjs          # parse scraper/evidence/*.html -> docs/scraped-specs.md
//
import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const FIELDS = ["team", "weapons", "weight", "power", "drive"];

const clean = (s) =>
  s.replace(/<[^>]+>/g, " ")
   .replace(/&#91;\d+&#93;/g, "")          // wiki citation markers [12]
   .replace(/&amp;/g, "&").replace(/&nbsp;/g, " ")
   .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(+d))
   .replace(/\s+/g, " ")
   .trim();

/** Pull the portable-infobox fields out of a wiki page's HTML. */
export function parseSpecs(html) {
  const out = {};
  for (const f of FIELDS) {
    const re = new RegExp(
      `data-source="${f}"[\\s\\S]{0,600}?pi-data-value[^>]*>([\\s\\S]{0,400}?)<\\/div>`,
      "i"
    );
    const m = html.match(re);
    if (m) {
      const v = clean(m[1]);
      if (v) out[f] = v.length > 120 ? v.slice(0, 117) + "…" : v;
    }
  }
  return out;
}

/** Map a scraped weapon description to one of our model archetypes. */
export function archetypeFromWeapon(weapons) {
  const w = (weapons || "").toLowerCase();
  if (!w) return null;
  if (/drum/.test(w)) return "drum_spinner";              // check before "eggbeater": eggbeater drums exist
  if (/vertical|drisc|disk spinner|eggbeater/.test(w)) return "vertical_spinner";
  if (/horizontal|shell spinner|full[- ]body|bar spinner|undercutter/.test(w)) return "horizontal_spinner";
  if (/flipper|launcher/.test(w)) return "flipper";
  if (/saw|hammer|axe/.test(w)) return "hammer_saw";
  if (/lift|clamp|crush|grappl|jaw|forks?/.test(w)) return "control";
  if (/spinner|disc|blade/.test(w)) return "horizontal_spinner";
  return null;
}

// ---- standalone mode: parse saved evidence, write a proof doc ----
if (import.meta.url === `file:///${process.argv[1].replace(/\\/g, "/")}`) {
  const EV = join(__dirname, "evidence");
  if (!existsSync(EV)) {
    console.log("No scraper/evidence/ yet — run `npm run scrape` first.");
    process.exit(0);
  }
  const bots = JSON.parse(readFileSync(join(ROOT, "data", "bots.json"), "utf8")).bots;
  const files = readdirSync(EV).filter((f) => f.endsWith(".html"));
  const rows = [];
  let ok = 0;
  for (const f of files) {
    const id = f.replace(/\.html$/, "");
    const specs = parseSpecs(readFileSync(join(EV, f), "utf8"));
    const arch = archetypeFromWeapon(specs.weapons);
    const bot = bots.find((b) => b.id === id);
    const match = bot && arch ? (arch === bot.archetype ? "✅ match" : `⚠️ ${arch}`) : "—";
    if (Object.keys(specs).length) ok++;
    rows.push({ id, name: bot ? bot.name : id, specs, arch, match });
    console.log(
      (bot ? bot.name : id).padEnd(20),
      (specs.weapons || "-").padEnd(42),
      (specs.weight || "-").padEnd(10),
      match
    );
  }
  let md = `# Structured data extracted via Bright Data\n\n`;
  md += `_Auto-generated by \`scraper/parse-specs.mjs\` from the HTML that \`scraper/scrape.mjs\` fetched through Bright Data's Web Unlocker._\n\n`;
  md += `These pages return **HTTP 403 to a plain scraper**, so none of the fields below are reachable without Bright Data. `;
  md += `The **Weapon** column is parsed from the wiki's portable-infobox markup and mapped to the model's weapon archetype; `;
  md += `the last column checks that mapping against the archetype used in \`data/bots.json\`.\n\n`;
  md += `Parsed **${ok}/${files.length}** pages.\n\n`;
  md += `| Robot | Team (scraped) | Weapon (scraped) | Weight | Archetype check |\n|---|---|---|---|---|\n`;
  for (const r of rows.sort((a, b) => a.name.localeCompare(b.name))) {
    md += `| ${r.name} | ${r.specs.team || "—"} | ${r.specs.weapons || "—"} | ${r.specs.weight || "—"} | ${r.match} |\n`;
  }
  md += `\n**Reading the archetype check:** ⚠️ rows are not errors — they are robots whose infobox lists **several weapons across different seasons** `;
  md += `(e.g. Bombshell's interchangeable weapons, HyperShock's season-to-season changes, Whiplash's lifter + spinner hybrid). `;
  md += `The dataset picks the archetype the robot is actually known for competing as; the scraper flags the disagreement so it can be reviewed rather than hidden.\n`;
  md += `\n_Note: the wiki infobox has **no career win-loss field**, so win-loss records are deliberately **not** auto-scraped — they stay researched and source-cited (see [DATA_SOURCES.md](DATA_SOURCES.md)). This pipeline refreshes the structured specs that drive the model's archetypes._\n`;
  mkdirSync(join(ROOT, "docs"), { recursive: true });
  writeFileSync(join(ROOT, "docs", "scraped-specs.md"), md);
  console.log(`\n✅ Parsed ${ok}/${files.length} pages → docs/scraped-specs.md`);
}
