// BattleScout AI — Bright Data enrichment + proof pipeline
// -----------------------------------------------------------
// Demonstrates Bright Data's core value: it fetches public BattleBots pages
// that BLOCK normal scrapers. For each robot we try a PLAIN fetch (usually
// blocked / rate-limited) and then the SAME url through Bright Data's Web
// Unlocker API (succeeds, returns fully-rendered HTML). The contrast is the
// proof, and it's written to docs/bright-data-proof.md.
//
// Zero npm dependencies — native fetch (Node 18+).
//
//   node scraper/scrape.mjs           # all robots
//   node scraper/scrape.mjs 3         # first 3 only (quick test)
//   node scraper/scrape.mjs --dry-run # no API calls
//
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

function loadEnv() {
  const p = join(__dirname, ".env");
  if (!existsSync(p)) return;
  for (const line of readFileSync(p, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
}
loadEnv();

const TOKEN = process.env.BRIGHTDATA_API_TOKEN;
const ZONE = process.env.BRIGHTDATA_ZONE || "web_unlocker1";
const DRY = process.argv.includes("--dry-run") || !TOKEN;
const LIMIT = Number(process.argv.find((a) => /^\d+$/.test(a))) || Infinity;

const db = JSON.parse(readFileSync(join(ROOT, "data", "bots.json"), "utf8"));
const EVID = join(__dirname, "evidence");

// The fan wiki that blocks plain scrapers — the perfect Bright Data demo.
const targetUrl = (bot) =>
  `https://battlebots.fandom.com/wiki/${encodeURIComponent(bot.name.replace(/!/g, "").trim().replace(/\s+/g, "_"))}`;

async function plainFetch(url) {
  try {
    const res = await fetch(url, { headers: { "user-agent": "curl/8.0 (plain-node-fetch)" } });
    return { status: res.status, ok: res.ok, chars: res.ok ? (await res.text()).length : 0 };
  } catch (e) {
    return { status: "ERR", ok: false, chars: 0, error: String(e.message || e) };
  }
}

async function brightDataFetch(url) {
  const res = await fetch("https://api.brightdata.com/request", {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${TOKEN}` },
    body: JSON.stringify({ zone: ZONE, url, format: "raw" }),
  });
  const body = await res.text();
  if (!res.ok) throw new Error(`Bright Data ${res.status}: ${body.slice(0, 200)}`);
  return body;
}

async function main() {
  console.log(`\n🤖 BattleScout AI — Bright Data proof run`);
  console.log(`   Target: battlebots.fandom.com (blocks plain scrapers)`);
  console.log(`   Zone: ${ZONE}\n`);

  if (DRY) {
    console.log(`⚠️  DRY RUN (no BRIGHTDATA_API_TOKEN). Would fetch, e.g.:`);
    db.bots.slice(0, 3).forEach((b) => console.log(`   • ${targetUrl(b)}`));
    console.log(`\n   Add credentials to scraper/.env then re-run.\n`);
    return;
  }

  mkdirSync(EVID, { recursive: true });
  const bots = db.bots.slice(0, LIMIT);
  const proof = [];
  let ok = 0;

  for (const b of bots) {
    const url = targetUrl(b);
    const plain = await plainFetch(url);
    try {
      const html = await brightDataFetch(url);
      writeFileSync(join(EVID, `${b.id}.html`), html);
      b.scrape = { url, ok: true, chars: html.length, plainStatus: plain.status };
      proof.push({ name: b.name, url, plain: plain.status, bd: `200 (${html.length.toLocaleString()} chars)` });
      ok++;
      console.log(`   ✅ ${b.name}: plain=${plain.status} → BrightData=200 [${html.length.toLocaleString()} chars]`);
    } catch (e) {
      b.scrape = { url, ok: false, error: String(e.message || e), plainStatus: plain.status };
      proof.push({ name: b.name, url, plain: plain.status, bd: `FAIL: ${e.message}` });
      console.log(`   ❌ ${b.name}: plain=${plain.status} → BrightData FAIL (${e.message})`);
    }
  }

  writeFileSync(join(ROOT, "data", "bots.enriched.json"), JSON.stringify(db, null, 2));

  // Committable proof doc
  let md = `# Bright Data — Proof of Use\n\n_Auto-generated by \`scraper/scrape.mjs\`. For each robot we requested the SAME BattleBots fan-wiki URL two ways._\n\n`;
  md += `A **plain fetch** (like a normal script would do) is blocked or rate-limited; the **Bright Data Web Unlocker** returns the full rendered page. This is why the project needs Bright Data — the data is otherwise unreachable.\n\n`;
  md += `| Robot | Plain fetch | Via Bright Data |\n|---|---|---|\n`;
  for (const p of proof) md += `| ${p.name} | ${p.plain} | ${p.bd} |\n`;
  md += `\nRaw fetched HTML for each robot is saved under \`scraper/evidence/\` as evidence.\n`;
  writeFileSync(join(ROOT, "docs", "bright-data-proof.md"), md);

  console.log(`\n✅ ${ok}/${bots.length} fetched via Bright Data.`);
  console.log(`   → data/bots.enriched.json`);
  console.log(`   → docs/bright-data-proof.md  (committable proof table)`);
  console.log(`   → scraper/evidence/*.html    (raw HTML evidence)\n`);
}

main().catch((e) => { console.error(e); process.exit(1); });
