// BattleScout AI — analysis engine
// Reads data/bots.json, computes the weapon-archetype meta, the Meta-Score
// leaderboard, and sample matchups, then writes docs/insights.md. Pure Node.
//
//   node analysis/analyze.mjs
//
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const { bots } = JSON.parse(readFileSync(join(ROOT, "data", "bots.json"), "utf8"));

const ARCH = ["vertical_spinner","horizontal_spinner","drum_spinner","flipper","hammer_saw","control"];
const LABEL = {vertical_spinner:"Vertical spinner",horizontal_spinner:"Horizontal spinner",drum_spinner:"Drum spinner",flipper:"Flipper",hammer_saw:"Hammer / saw",control:"Control"};
const RAW = {
  "vertical_spinner|horizontal_spinner":0.58,"vertical_spinner|drum_spinner":0.53,
  "vertical_spinner|flipper":0.62,"vertical_spinner|hammer_saw":0.60,"vertical_spinner|control":0.60,
  "horizontal_spinner|drum_spinner":0.50,"horizontal_spinner|flipper":0.55,"horizontal_spinner|hammer_saw":0.52,
  "horizontal_spinner|control":0.45,"drum_spinner|flipper":0.55,"drum_spinner|hammer_saw":0.53,
  "drum_spinner|control":0.53,"flipper|hammer_saw":0.50,"flipper|control":0.52,"hammer_saw|control":0.50
};
const archProb = (a,b) => a===b?0.5:(RAW[a+"|"+b]??(RAW[b+"|"+a]!==undefined?1-RAW[b+"|"+a]:0.5));
const sigmoid = x => 1/(1+Math.exp(-x));
const winRate = b => (b.wins+b.losses)>0 ? b.wins/(b.wins+b.losses) : b.reputation/100;
function predict(A,B){
  const logit = 4.0*(winRate(A)-winRate(B)) + 1.2*(A.koRate-B.koRate) + 6.0*(archProb(A.archetype,B.archetype)-0.5)*0.5;
  return sigmoid(logit);
}
const metaScore = bot => {
  let s=0,n=0; for(const o of bots){ if(o.id!==bot.id){ s+=predict(bot,o); n++; } } return n?s/n:0.5;
};
const byId = id => bots.find(b=>b.id===id);

// Archetype meta
const sums={}, counts={}; ARCH.forEach(a=>{sums[a]=0;counts[a]=0;});
for(const A of bots) for(const B of bots){ if(A.id!==B.id){ sums[A.archetype]+=predict(A,B); counts[A.archetype]++; } }
const meta = ARCH.map(a=>({a,rate:counts[a]?sums[a]/counts[a]:0.5})).sort((x,y)=>y.rate-x.rate);

// Meta-Score leaderboard (bots with a record)
const board = bots.filter(b=>b.wins+b.losses>0)
  .map(b=>({name:b.name,win:winRate(b),meta:metaScore(b)}))
  .sort((x,y)=>y.meta-x.meta);

const featured = [["orbitron","tombstone"],["endgame","tombstone"],["biteforce","endgame"],["hydra","tombstone"]];

let md = `# BattleScout AI — Data Insights\n\n_Auto-generated by \`analysis/analyze.mjs\` from \`data/bots.json\` (${bots.length} heavyweights)._\n\n`;
md += `## Headline: the weapon-archetype meta\n\nAverage predicted win rate across all ${bots.length*(bots.length-1)} directional matchups:\n\n| Archetype | Avg win rate |\n|---|---|\n`;
for(const m of meta) md += `| ${LABEL[m.a]} | ${(m.rate*100).toFixed(1)}% |\n`;
md += `\n**Takeaway:** ${LABEL[meta[0].a]}s top the meta at ${(meta[0].rate*100).toFixed(1)}%; ${LABEL[meta[meta.length-1].a].toLowerCase()}s sit at the bottom (${(meta[meta.length-1].rate*100).toFixed(1)}%).\n\n`;

md += `## Meta-Score leaderboard (top 8)\n\nMeta Score = a bot's average predicted win probability vs the entire field. It rewards a strong archetype, not just a padded record — note how the #1 by Meta Score can differ from the #1 by raw win rate.\n\n| # | Robot | Win rate | Meta Score |\n|---|---|---|---|\n`;
board.slice(0,8).forEach((r,i)=>{ md += `| ${i+1} | ${r.name} | ${(r.win*100).toFixed(0)}% | ${(r.meta*100).toFixed(0)}% |\n`; });

md += `\n## Featured matchups\n\n`;
for(const [x,y] of featured){
  const A=byId(x),B=byId(y),p=predict(A,B);
  const w=p>=0.5?A:B, wp=Math.round((p>=0.5?p:1-p)*100);
  md += `- **${A.name} vs ${B.name}** → ${w.name} favored (${wp}%)\n`;
}
md += `\n_Records are seed estimates refreshed from the live web via the Bright Data pipeline (\`npm run scrape\`)._\n`;

mkdirSync(join(ROOT,"docs"),{recursive:true});
writeFileSync(join(ROOT,"docs","insights.md"), md);
console.log(md);
console.log("\n✅ Wrote docs/insights.md");
