// BattleScout AI — analysis engine
// Reads data/bots.json, computes the weapon-archetype meta and sample matchups,
// and writes docs/insights.md. Pure Node, no dependencies.
//
//   node analysis/analyze.mjs
//
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const { bots } = JSON.parse(readFileSync(join(ROOT, "data", "bots.json"), "utf8"));

const ARCH = ["vertical_spinner","horizontal_spinner","drum_spinner","flipper","hammer_saw","control"];
const LABEL = {vertical_spinner:"Vertical spinner",horizontal_spinner:"Horizontal spinner",drum_spinner:"Drum spinner",flipper:"Flipper",hammer_saw:"Hammer / saw",control:"Control"};
const RAW = {
  "vertical_spinner|horizontal_spinner":0.58,"vertical_spinner|drum_spinner":0.53,
  "vertical_spinner|flipper":0.62,"vertical_spinner|hammer_saw":0.60,"vertical_spinner|control":0.60,
  "horizontal_spinner|drum_spinner":0.50,"horizontal_spinner|flipper":0.55,"horizontal_spinner|hammer_saw":0.52,
  "horizontal_spinner|control":0.45,"drum_spinner|flipper":0.55,"drum_spinner|hammer_saw":0.53,
  "drum_spinner|control":0.53,"flipper|hammer_saw":0.50,"flipper|control":0.52,"hammer_saw|control":0.50
};
const archProb = (a,b) => a===b?0.5:(RAW[a+"|"+b]??(RAW[b+"|"+a]!==undefined?1-RAW[b+"|"+a]:0.5));
const sigmoid = x => 1/(1+Math.exp(-x));
function predict(A,B){
  const ap = archProb(A.archetype,B.archetype);
  const logit = 0.62*((ap-0.5)*4) + 0.38*((A.reputation-B.reputation)/40);
  return sigmoid(logit);
}
const byId = id => bots.find(b=>b.id===id);

// Meta: average win rate per archetype across all matchups
const sums={}, counts={};
ARCH.forEach(a=>{sums[a]=0;counts[a]=0;});
for(const A of bots) for(const B of bots){
  if(A.id===B.id) continue;
  sums[A.archetype]+=predict(A,B); counts[A.archetype]++;
}
const meta = ARCH.map(a=>({a,rate:counts[a]?sums[a]/counts[a]:0.5})).sort((x,y)=>y.rate-x.rate);

// Featured matchups for the write-up
const featured = [["orbitron","tombstone"],["endgame","tombstone"],["biteforce","endgame"],["hydra","tombstone"]];

let md = `# BattleScout AI — Data Insights\n\n_Auto-generated by \`analysis/analyze.mjs\` from \`data/bots.json\` (${bots.length} heavyweights)._\n\n`;
md += `## Headline: the weapon-archetype meta\n\nAverage predicted win rate across all ${bots.length*(bots.length-1)} directional matchups:\n\n| Archetype | Avg win rate |\n|---|---|\n`;
for(const m of meta) md += `| ${LABEL[m.a]} | ${(m.rate*100).toFixed(1)}% |\n`;
md += `\n**Takeaway:** ${LABEL[meta[0].a]}s top the meta at ${(meta[0].rate*100).toFixed(1)}%, while ${LABEL[meta[meta.length-1].a].toLowerCase()}s sit at the bottom (${(meta[meta.length-1].rate*100).toFixed(1)}%).\n\n`;
md += `## Featured matchups\n\n`;
for(const [x,y] of featured){
  const A=byId(x),B=byId(y),p=predict(A,B);
  const w=p>=0.5?A:B, wp=Math.round((p>=0.5?p:1-p)*100);
  md += `- **${A.name} vs ${B.name}** → ${w.name} favored (${wp}%)\n`;
}
md += `\n_Note: \`record\` and \`sentiment\` fields are populated by the Bright Data pipeline (\`npm run scrape\`); the seed model runs on weapon archetype + reputation index._\n`;

mkdirSync(join(ROOT,"docs"),{recursive:true});
writeFileSync(join(ROOT,"docs","insights.md"), md);
console.log(md);
console.log("\n✅ Wrote docs/insights.md");
